fragment FieldFragment on Field {
  label
  name
  hidden
  maxLength
  size
  required
  autoComplete
  options {
    label
    value
  }
  optionsCaption
  elementName
  mask
  pattern
  additionalData {
    ... on PostalCodeData {
      forgottenURL
    }
  }
}

fragment DisplayFragment on DisplayDefinition {
  name
  delimiter
  delimiterAfter
}

query AddressRules($countries: [String!]!) {
  countriesData(countries: $countries) {
    countryISO
    addressFields {
      city {
        ...FieldFragment
      }
      complement {
        ...FieldFragment
      }
      country {
        ...FieldFragment
      }
      neighborhood {
        ...FieldFragment
      }
      number {
        ...FieldFragment
      }
      postalCode {
        ...FieldFragment
      }
      receiverName {
        ...FieldFragment
      }
      reference {
        ...FieldFragment
      }
      state {
        ...FieldFragment
      }
      street {
        ...FieldFragment
      }
    }
    display {
      minimal {
        ...DisplayFragment
      }
      brief {
        ...DisplayFragment
      }
      compact {
        ...DisplayFragment
      }
      extended {
        ...DisplayFragment
      }
    }
    locationSelect {
      countryData
      fields {
        ...FieldFragment
      }
    }
  }
}
